# Generated by Django 5.2.11 on 2026-02-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_column='isPublished', default=False)),
                ('students_enrolled', models.IntegerField(db_column='studentsEnrolled', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='ExtraNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], db_column='mediaType', max_length=20, null=True)),
                ('media_url', models.TextField(blank=True, db_column='mediaUrl', null=True)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'ExtraNews',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.TextField(blank=True, db_column='imageUrl', null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(db_column='isPublished', default=False)),
                ('published_at', models.DateTimeField(blank=True, db_column='publishedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('riddle', 'Riddle'), ('logic', 'Logic'), ('math', 'Math')], default='riddle', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('solved_by', models.IntegerField(db_column='solvedBy', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Puzzles',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(db_column='shortName', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('image_url', models.TextField(blank=True, db_column='imageUrl', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='student', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.TextField(blank=True, db_column='avatarUrl', null=True)),
                ('group_id_legacy', models.IntegerField(blank=True, db_column='groupId', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('chat', models.ForeignKey(db_column='chatId', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.chat')),
                ('sender', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='school.user')),
            ],
            options={
                'db_table': 'ChatMessages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='file', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.ForeignKey(db_column='messageId', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.chatmessage')),
            ],
            options={
                'db_table': 'ChatMessageAttachments',
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.TextField(blank=True, db_column='videoUrl', null=True)),
                ('video_type', models.CharField(db_column='videoType', default='youtube', max_length=20)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(db_column='courseId', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.course')),
            ],
            options={
                'db_table': 'CourseLessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLessonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.IntegerField(db_column='correctAnswer', default=0)),
                ('lesson', models.ForeignKey(db_column='lessonId', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school.courselesson')),
            ],
            options={
                'db_table': 'CourseLessonQuestions',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('material', 'Material'), ('test', 'Test')], default='material', max_length=20)),
                ('is_published', models.BooleanField(db_column='isPublished', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('group', models.ForeignKey(blank=True, db_column='groupId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group')),
                ('subject', models.ForeignKey(blank=True, db_column='subjectId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'db_table': 'LearningMaterials',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('youtube', 'YouTube'), ('link', 'Link'), ('image', 'Image'), ('file', 'File')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, db_column='fileSize', max_length=50, null=True)),
                ('material', models.ForeignKey(db_column='materialId', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.learningmaterial')),
            ],
            options={
                'db_table': 'LearningMaterialAttachments',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField(db_column='scheduledDate')),
                ('start_time', models.CharField(db_column='startTime', max_length=10)),
                ('end_time', models.CharField(db_column='endTime', max_length=10)),
                ('meeting_link', models.TextField(blank=True, db_column='meetingLink', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('grading', 'Grading')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('group', models.ForeignKey(blank=True, db_column='groupId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group')),
                ('subject', models.ForeignKey(blank=True, db_column='subjectId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_type', models.CharField(db_column='targetType', default='all', max_length=20)),
                ('is_anonymous', models.BooleanField(db_column='isAnonymous', default=False)),
                ('is_multiple_choice', models.BooleanField(db_column='isMultipleChoice', default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('ends_at', models.DateField(db_column='endsAt')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('target_group', models.ForeignKey(blank=True, db_column='targetGroupId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group')),
            ],
            options={
                'db_table': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(db_column='pollId', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='school.poll')),
            ],
            options={
                'db_table': 'PollOptions',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subjectId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('homework', 'Homework'), ('project', 'Project'), ('test', 'Test'), ('practice', 'Practice'), ('classwork', 'Classwork')], default='homework', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_column='dueDate', null=True)),
                ('max_grade', models.IntegerField(db_column='maxGrade', default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('group', models.ForeignKey(blank=True, db_column='groupId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group')),
                ('subject', models.ForeignKey(blank=True, db_column='subjectId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject')),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'Link'), ('file', 'File'), ('image', 'Image')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('file_size', models.CharField(blank=True, db_column='fileSize', max_length=50, null=True)),
                ('task', models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='school.task')),
            ],
            options={
                'db_table': 'TaskAttachments',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('overdue', 'Overdue'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('teacher_comment', models.TextField(blank=True, db_column='teacherComment', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submittedAt', null=True)),
                ('graded_at', models.DateTimeField(blank=True, db_column='gradedAt', null=True)),
                ('task', models.ForeignKey(db_column='taskId', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.task')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='school.user')),
            ],
            options={
                'db_table': 'TaskSubmissions',
                'unique_together': {('task', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_column='fileName', max_length=255)),
                ('file_url', models.TextField(db_column='fileUrl')),
                ('file_size', models.CharField(blank=True, db_column='fileSize', max_length=50, null=True)),
                ('file_type', models.CharField(db_column='fileType', default='file', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploadedAt')),
                ('submission', models.ForeignKey(db_column='submissionId', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='school.tasksubmission')),
            ],
            options={
                'db_table': 'SubmissionFiles',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#FF9A00', max_length=7)),
                ('total_points', models.IntegerField(db_column='totalPoints', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('group', models.ForeignKey(blank=True, db_column='groupId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group')),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='StudentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('source_type', models.CharField(db_column='sourceType', max_length=50)),
                ('source_id', models.IntegerField(blank=True, db_column='sourceId', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True, db_column='earnedAt')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='school.user')),
            ],
            options={
                'db_table': 'StudentPoints',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_column='isRead', default=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school.user')),
            ],
            options={
                'db_table': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(db_column='paidAmount', decimal_places=2, default=0, max_digits=10)),
                ('installments', models.IntegerField(default=1)),
                ('current_installment', models.IntegerField(db_column='currentInstallment', default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, db_column='dueDate', null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_column='paidAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='school.user')),
            ],
            options={
                'db_table': 'Invoices',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to='school.user'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='joinedAt')),
                ('team', models.ForeignKey(db_column='teamId', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='school.team')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='school.user')),
            ],
            options={
                'db_table': 'TeamMembers',
                'unique_together': {('team', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_column='votedAt')),
                ('option', models.ForeignKey(db_column='optionId', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='school.polloption')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='school.user')),
            ],
            options={
                'db_table': 'PollVotes',
                'unique_together': {('option', 'student')},
            },
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True, db_column='gradedAt')),
                ('lesson', models.ForeignKey(db_column='lessonId', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.lesson')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='school.user')),
            ],
            options={
                'db_table': 'LessonGrades',
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='joinedAt')),
                ('group', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='school.group')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='school.user')),
            ],
            options={
                'db_table': 'GroupStudents',
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='joinedAt')),
                ('chat', models.ForeignKey(db_column='chatId', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='school.chat')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to='school.user')),
            ],
            options={
                'db_table': 'ChatParticipants',
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('sick', 'Sick'), ('excused', 'Excused')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now=True, db_column='markedAt')),
                ('lesson', models.ForeignKey(db_column='lessonId', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.lesson')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, to='school.user')),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
