# Generated by Django 5.2.11 on 2026-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_user_registered_at_alter_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video_url',
            field=models.TextField(blank=True, db_column='videoUrl', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
