# Generated by Django 5.2.11 on 2026-02-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_news_link_news_video_url_news_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
