# Generated by Django 5.2.11 on 2026-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_user_is_active_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
