# Generated by Django 5.2.11 on 2026-02-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_url', models.TextField(db_column='receiptUrl')),
                ('receipt_name', models.CharField(db_column='receiptName', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewedAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('invoice', models.ForeignKey(db_column='invoiceId', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='school.invoice')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoice_receipts', to='school.user')),
                ('student', models.ForeignKey(db_column='studentId', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipts', to='school.user')),
            ],
            options={
                'db_table': 'InvoicePaymentReceipts',
            },
        ),
    ]
