# Generated by Django 5.2.11 on 2026-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_invoicepaymentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, db_column='birthDate', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_column='firstName', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_column='lastName', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_address',
            field=models.TextField(blank=True, db_column='registrationAddress', null=True),
        ),
    ]
