name: Build & Deploy (Docker) to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: azure-webapp-${{ github.ref }}
  cancel-in-progress: true

env:
  GHCR_NAMESPACE: denis-roman
  IMAGE_NAME: diplom-backend
  WEBAPP_NAME: diplom-backend-denis-01

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 22c4cd14-45ac-4e54-a83a-297c4a6fcd5e
          tenant-id: 55a2c33f-4244-4858-8de0-af7e2b953913
          subscription-id: 4720e667-4be2-47b6-9435-5d7abab91eb0

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images: ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
